name: gnofract4d # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '4.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Generates fractals such as the Mandelbrot and Julia sets # 79 char long summary
description: |
  Gnofract 4D is a fast, flexible program to generate beautiful fractal images.
  This includes well-known fractals like the Mandelbrot set, and you can define 
  your own using a simple programming language. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  gnofract4d:
    command: bin/gnofract4d

parts:
  gnofract4d:
    plugin: python
    python-version: python3
    source: .
    build-packages: [g++, libpng-dev, libjpeg-dev, libcairo2-dev, python3-dev, python3-cairo, python3-gi-cairo, pkg-config, libgirepository1.0-dev]
    stage-packages: 
      - g++
      - libpng-dev
      - libjpeg8
      - libcairo2-dev
      - python3-cairo
      - python3-gi-cairo
      - libgirepository1.0-dev
      - python3-gi
      - gobject-introspection
      - gir1.2-gtk-3.0
      - python3-all-dev
      - gir1.2-glib-2.0
      - gir1.2-gnomedesktop-3.0 #gir1.2-webkit2-4.0', gir1.2-notify-0.7, libc-bin
